/*
RIBBIT API v4

ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  CONNECTApi,
  InsightsApi,
  ReportsApi,
  TokenApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { ValidiFiBankLoginCustom } from "./client-custom";

export class ValidiFiBankLogin extends ValidiFiBankLoginCustom {
  readonly cONNECT: CONNECTApi;
  readonly insights: InsightsApi;
  readonly reports: ReportsApi;
  readonly token: TokenApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.cONNECT = new CONNECTApi(configuration);
    this.insights = new InsightsApi(configuration);
    this.reports = new ReportsApi(configuration);
    this.token = new TokenApi(configuration);
  }

}
