/*
RIBBIT API v4

ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TokenCreateRequest
 */
export interface TokenCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof TokenCreateRequest
     */
    'clientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenCreateRequest
     */
    'clientSecret'?: string;
}

